---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata: 
  labels:
    custom-kubelet: max-pods-500
    machineconfiguration.openshift.io/role: ran
  name: ran
spec:
  machineConfigSelector:
    matchExpressions:
      - {
          key: machineconfiguration.openshift.io/role,
          operator: In,
          values: [worker, ran]
        }
  paused: false
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/ran: ""

# oc patch mcp ran-du -p '{"spec": {"paused": true}}'