---
apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  name: openshift-node-performance-profile-{{ $.Values.mcp.net_function }}.{{ $.Values.mcp.mcp_profile }}
spec:
  additionalKernelArgs:
  - idle=poll
  - rcupdate.rcu_normal_after_boot=0
  cpu:
    isolated: 2-31,34-63
    reserved: 0-1,32-33
  hugepages:
    defaultHugepagesSize: 1G
    pages:
    - count: 64
      size: 1G
  machineConfigPoolSelector:
    pools.operator.machineconfiguration.openshift.io/{{ $.Values.mcp.net_function }}.{{ $.Values.mcp.mcp_profile }}: ""
  net:
    userLevelNetworking: true
  nodeSelector:
    node-role.kubernetes.io/{{ $.Values.mcp.net_function }}.{{ $.Values.mcp.mcp_profile }}: ""
  numa:
    topologyPolicy: restricted
  realTimeKernel:
    enabled: true