apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 55-masters-chrony-configuration
  labels:
    machineconfiguration.openshift.io/role: master
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,{{ $.Values.global.chrony_conf | b64enc }}
          verification: {}
        filesystem: root
        mode: 420
        overwrite: true        
        path: /etc/chrony.conf
