{{- $schedulable := true }}
{{ if hasKey $.Values "cluster"  -}}
{{- $schedulable := $.Values.cluster.mastersSchedulable | default true }}
{{- end }}
{{- if eq $schedulable true }}
---
apiVersion: config.openshift.io/v1
kind: Scheduler
metadata:
  name: cluster
spec:
  mastersSchedulable: true
{{- end }}