{{- if eq ($.Values.cluster.mastersSchedulable | default true) true }}
---
apiVersion: config.openshift.io/v1
kind: Scheduler
metadata:
  name: cluster
spec:
  mastersSchedulable: true
#  mastersSchedulable: false
{{- end }}