{{- $schedulable := $.Values.cluster.mastersSchedulable | default true }}
{{- if eq $schedulable true }}
---
apiVersion: config.openshift.io/v1
kind: Scheduler
metadata:
  name: cluster
spec:
  mastersSchedulable: true
#  mastersSchedulable: false
{{- end }}