---
apiVersion: tuned.openshift.io/v1
kind: Tuned
metadata:
  name: performance-patch-{{ $.Values.mcp.net_function }}.{{ $.Values.mcp.mcp_profile }}
  namespace: openshift-cluster-node-tuning-operator
spec:
  profile:
  - data: |
      [main]
      summary=Configuration changes profile inherited from performance created tuned
      include=openshift-node-performance-openshift-node-performance-profile-{{ $.Values.mcp.net_function }}.{{ $.Values.mcp.mcp_profile }}
      [bootloader]
      cmdline_crash=nohz_full=2-31,34-63
      [sysctl]
      kernel.timer_migration=1
      [scheduler]
      group.ice-ptp=0:f:10:*:ice-ptp.*
      [service]
      service.stalld=start,enable
    name: performance-patch-{{ $.Values.mcp.net_function }}.{{ $.Values.mcp.mcp_profile }}
  recommend:
  - machineConfigLabels:
      #machineconfiguration.openshift.io/role: {{ $.Values.mcp.net_function }}.{{ $.Values.mcp.mcp_profile }}
      machineconfiguration.openshift.io/role: master
    priority: 19
    profile: performance-patch-{{ $.Values.mcp.net_function }}.{{ $.Values.mcp.mcp_profile }}
