---
apiVersion: tuned.openshift.io/v1
kind: Tuned
metadata:
  name: performance-patch-master-sno-vm
  namespace: openshift-cluster-node-tuning-operator
spec:
  profile:
  - data: |
      [main]
      summary=Configuration changes profile inherited from performance created tuned
      include=openshift-node-performance-openshift-node-performance-profile-master-sno-vm
      [bootloader]
      cmdline_crash=nohz_full=4-15
      [sysctl]
      kernel.timer_migration=1
      [scheduler]
      group.ice-ptp=0:f:10:*:ice-ptp.*
      [service]
      service.stalld=start,enable
    name: performance-patch-master-sno-vm
  recommend:
  - machineConfigLabels:
      #machineconfiguration.openshift.io/role: master-sno-vm
      machineconfiguration.openshift.io/role: master
    priority: 19
    profile: performance-patch-master-sno-vm
