kind: ConfigMap
apiVersion: v1
metadata:
  name: openshift-user-ca
  namespace: openshift-controller-manager
data:
  {{ $.Values.mgmt.registry.url }}: {{ toYaml $.Values.global.ai.ca | indent 2 }}
  updateservice-registry: {{ toYaml $.Values.global.ai.ca | indent 2 }}  
  ca-bundle.crt: {{ toYaml $.Values.global.ai.ca | indent 2 }}  