---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: idm01-ldap 
    mappingMethod: claim 
    type: LDAP
    ldap:
      attributes:
        id: 
        - dn
        email: 
        - mail
        name: 
        - cn
        preferredUsername: 
        - uid
      bindDN: "uid=ocp-binddn,cn=sysaccounts,cn=etc,dc=tmetse,dc=lab" 
      bindPassword: 
        name: idm01-binddn-secret
      ca: 
        name: registry-ca-local
      insecure: false 
      url: "ldap://idm01.tmetse.lab/cn=users,cn=accounts,dc=tmetse,dc=lab?uid?sub?(uid=*)"
